linear_version_path = "1-test-version/GaussianOpenMP.exe"
test_image_path = "test.png"
binary_input_default = "1-test-version/image.in"
binary_output_default = "1-test-version/image.out"
test_imgs_dir = "./test_imgs/"
checker_binares_dir = "./tests/"
checker_answers_dir = "./answers/"